COMMENT ON COLUMN date_dim.d_date_sk IS '日付キー（主キー、他テーブルから参照される）';
COMMENT ON COLUMN date_dim.d_date_id IS '日付ID（業務的な識別子、例：YYYYMMDD）';
COMMENT ON COLUMN date_dim.d_date IS '実際の日付（日付型）';
COMMENT ON COLUMN date_dim.d_month_seq IS '月の連番（基準日からの月数）';
COMMENT ON COLUMN date_dim.d_week_seq IS '週の連番（基準日からの週数）';
COMMENT ON COLUMN date_dim.d_quarter_seq IS '四半期の連番（基準日からの四半期数）';
COMMENT ON COLUMN date_dim.d_year IS '暦年（西暦）';
COMMENT ON COLUMN date_dim.d_dow IS '曜日番号（日曜=0～土曜=6）';
COMMENT ON COLUMN date_dim.d_moy IS '月内の何番目の月（1=1月〜12=12月）';
COMMENT ON COLUMN date_dim.d_dom IS '月内の日（1〜31）';
COMMENT ON COLUMN date_dim.d_qoy IS '四半期内の月番号（1〜3）';
COMMENT ON COLUMN date_dim.d_fy_year IS '会計年度';
COMMENT ON COLUMN date_dim.d_fy_quarter_seq IS '会計年度ベースの四半期連番';
COMMENT ON COLUMN date_dim.d_fy_week_seq IS '会計年度ベースの週連番';
COMMENT ON COLUMN date_dim.d_day_name IS '曜日名（例：Sunday, Monday）';
COMMENT ON COLUMN date_dim.d_quarter_name IS '四半期名（例：Q1, Q2）';
COMMENT ON COLUMN date_dim.d_holiday IS '祝日であるか（true/false）';
COMMENT ON COLUMN date_dim.d_weekend IS '週末であるか（土日か）';
COMMENT ON COLUMN date_dim.d_following_holiday IS '翌日が祝日であるか（true/false）';
COMMENT ON COLUMN date_dim.d_first_dom IS 'その月の初日の曜日（0=日曜～6=土曜）';
COMMENT ON COLUMN date_dim.d_last_dom IS 'その月の最終日（日付）';
COMMENT ON COLUMN date_dim.d_same_day_ly IS '前年同日の日付キー';
COMMENT ON COLUMN date_dim.d_same_day_lq IS '前四半期同日の日付キー';
COMMENT ON COLUMN date_dim.d_current_day IS '現在日かどうか（true/false）';
COMMENT ON COLUMN date_dim.d_current_week IS '現在週かどうか（true/false）';
COMMENT ON COLUMN date_dim.d_current_month IS '現在月かどうか（true/false）';
COMMENT ON COLUMN date_dim.d_current_quarter IS '現在四半期かどうか（true/false）';
COMMENT ON COLUMN date_dim.d_current_year IS '現在年かどうか（true/false）';
